directories:
  data: "scripts/data" 
  jsons: "scripts/data/jsons"
  logs: "logs"
  chat_logs: "scripts/data/chat_logs"

logger:
  level: "DEBUG"  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"  # Log message format
  datefmt: "%Y-%m-%d %H:%M:%S"  # Date format for log messages
  filename: "legal_notebook.log"  # Log file name
  max_bytes: 10000000 # 2MB
  backup_count: 5

aiconfig:
  default_encoding: "o200k_base"

vector_database:
  search_limit: 10  # Number of relevant chunks to retrieve from vector search
  root_path: "S:\\JustinPinter\\Legal_Notebook"